USE cake_shop;

INSERT INTO category (name, description, image_url) VALUES
('Cakes','Celebration and everyday cakes.','assets/images/categories/category-1.jpg'),
('Cupcakes','Individual cupcakes for parties and treats.','assets/images/categories/category-2.jpg'),
('Pudding','Creamy layered pudding desserts.','assets/images/categories/category-3.jpg'),
('Cookies','Freshly baked cookies and cookie boxes.','assets/images/categories/category-4.jpg'),
('Cheesecakes','Classic and flavoured cheesecakes.','assets/images/categories/category-5.jpg'),
('Brownies','Rich chocolate brownie selections.','assets/images/categories/category-6.jpg');

INSERT INTO promo_code (code, discount_type, discount_value, valid_until, is_active) VALUES
('WELCOME10','percentage',10.00,NULL,1),
('SWEET500','fixed',500.00,NULL,1);

INSERT INTO product (category_id, name, description, price, size, image_url, stock_qty, is_available) VALUES
(1,'Classic Vanilla Cake','Soft layered classic vanilla cake prepared for celebrations and sharing.',2640.00,'6-inch','assets/images/products/product-001.jpg',21,1),
(1,'Rich Chocolate Cake','Soft layered rich chocolate cake prepared for celebrations and sharing.',2780.00,'6-inch','assets/images/products/product-002.jpg',22,1),
(1,'Blueberry Velvet Cake','Soft layered blueberry velvet cake prepared for celebrations and sharing.',2920.00,'6-inch','assets/images/products/product-003.jpg',23,1),
(1,'Vanilla Berry Cake','Soft layered vanilla berry cake prepared for celebrations and sharing.',3060.00,'6-inch','assets/images/products/product-004.jpg',24,1),
(1,'Mocha Dream Cake','Soft layered mocha dream cake prepared for celebrations and sharing.',3200.00,'6-inch','assets/images/products/product-005.jpg',25,1),
(1,'Caramel Crunch Cake','Soft layered caramel crunch cake prepared for celebrations and sharing.',3340.00,'6-inch','assets/images/products/product-006.jpg',26,1),
(1,'Coffee Cream Cake','Soft layered coffee cream cake prepared for celebrations and sharing.',3480.00,'6-inch','assets/images/products/product-007.jpg',27,1),
(1,'Lemon Butter Cake','Soft layered lemon butter cake prepared for celebrations and sharing.',3620.00,'6-inch','assets/images/products/product-008.jpg',28,1),
(1,'Strawberry Cloud Cake','Soft layered strawberry cloud cake prepared for celebrations and sharing.',3760.00,'6-inch','assets/images/products/product-009.jpg',29,1),
(1,'Blueberry Bliss Cake','Soft layered blueberry bliss cake prepared for celebrations and sharing.',3900.00,'6-inch','assets/images/products/product-010.jpg',30,1),
(1,'Cookies & Cream Cake','Soft layered cookies & cream cake prepared for celebrations and sharing.',4040.00,'6-inch','assets/images/products/product-011.jpg',31,1),
(1,'Dark Chocolate Fudge Cake','Soft layered dark chocolate fudge cake prepared for celebrations and sharing.',4180.00,'6-inch','assets/images/products/product-012.jpg',32,1),
(1,'Pistachio Rose Cake','Soft layered pistachio rose cake prepared for celebrations and sharing.',4320.00,'6-inch','assets/images/products/product-013.jpg',33,1),
(1,'Coconut Cream Cake','Soft layered coconut cream cake prepared for celebrations and sharing.',4460.00,'6-inch','assets/images/products/product-014.jpg',34,1),
(1,'Mango Celebration Cake','Soft layered mango celebration cake prepared for celebrations and sharing.',4600.00,'6-inch','assets/images/products/product-015.jpg',35,1),
(1,'Red Velvet Cake','Soft layered red velvet cake prepared for celebrations and sharing.',4740.00,'6-inch','assets/images/products/product-016.jpg',36,1),
(1,'Black Forest Cake','Soft layered black forest cake prepared for celebrations and sharing.',4880.00,'6-inch','assets/images/products/product-017.jpg',37,1),
(1,'Marble Delight Cake','Soft layered marble delight cake prepared for celebrations and sharing.',5020.00,'6-inch','assets/images/products/product-018.jpg',38,1),
(1,'Salted Caramel Cake','Soft layered salted caramel cake prepared for celebrations and sharing.',5160.00,'6-inch','assets/images/products/product-019.jpg',39,1),
(1,'Birthday Sprinkle Cake','Soft layered birthday sprinkle cake prepared for celebrations and sharing.',5300.00,'6-inch','assets/images/products/product-020.jpg',40,1),

(2,'Vanilla Cupcake','Fresh vanilla cupcake with a smooth topping and soft centre.',485.00,'Single','assets/images/products/product-021.jpg',31,1),
(2,'Chocolate Cupcake','Fresh chocolate cupcake with a smooth topping and soft centre.',520.00,'Single','assets/images/products/product-022.jpg',32,1),
(2,'Red Velvet Cupcake','Fresh red velvet cupcake with a smooth topping and soft centre.',555.00,'Single','assets/images/products/product-023.jpg',33,1),
(2,'Blueberry Cupcake','Fresh blueberry cupcake with a smooth topping and soft centre.',590.00,'Single','assets/images/products/product-024.jpg',34,1),
(2,'Strawberry Cupcake','Fresh strawberry cupcake with a smooth topping and soft centre.',625.00,'Single','assets/images/products/product-025.jpg',35,1),
(2,'Caramel Cupcake','Fresh caramel cupcake with a smooth topping and soft centre.',660.00,'Single','assets/images/products/product-026.jpg',36,1),
(2,'Coffee Cupcake','Fresh coffee cupcake with a smooth topping and soft centre.',695.00,'Single','assets/images/products/product-027.jpg',37,1),
(2,'Lemon Cupcake','Fresh lemon cupcake with a smooth topping and soft centre.',730.00,'Single','assets/images/products/product-028.jpg',38,1),
(2,'Cookies & Cream Cupcake','Fresh cookies & cream cupcake with a smooth topping and soft centre.',765.00,'Single','assets/images/products/product-029.jpg',39,1),
(2,'Salted Caramel Cupcake','Fresh salted caramel cupcake with a smooth topping and soft centre.',800.00,'Single','assets/images/products/product-030.jpg',40,1),
(2,'Mango Cupcake','Fresh mango cupcake with a smooth topping and soft centre.',835.00,'Single','assets/images/products/product-031.jpg',41,1),
(2,'Coconut Cupcake','Fresh coconut cupcake with a smooth topping and soft centre.',870.00,'Single','assets/images/products/product-032.jpg',42,1),
(2,'Pistachio Cupcake','Fresh pistachio cupcake with a smooth topping and soft centre.',905.00,'Single','assets/images/products/product-033.jpg',43,1),
(2,'Birthday Cupcake','Fresh birthday cupcake with a smooth topping and soft centre.',940.00,'Single','assets/images/products/product-034.jpg',44,1),
(2,'Dark Chocolate Cupcake','Fresh dark chocolate cupcake with a smooth topping and soft centre.',975.00,'Single','assets/images/products/product-035.jpg',45,1),

(3,'Classic Vanilla Pudding','Creamy layered classic pudding served chilled.',1005.00,'Mini cup','assets/images/products/product-036.jpg',19,1),
(3,'Caramel Pudding','Creamy layered caramel pudding served chilled.',1060.00,'Mini cup','assets/images/products/product-037.jpg',20,1),
(3,'Chocolate Pudding','Creamy layered chocolate pudding served chilled.',1115.00,'Mini cup','assets/images/products/product-038.jpg',21,1),
(3,'Vanilla Bean Pudding','Creamy layered vanilla pudding served chilled.',1170.00,'Mini cup','assets/images/products/product-039.jpg',22,1),
(3,'Berry Pudding','Creamy layered berry pudding served chilled.',1225.00,'Mini cup','assets/images/products/product-040.jpg',23,1),
(3,'Cinnamon Pudding','Creamy layered cinnamon pudding served chilled.',1280.00,'Mini cup','assets/images/products/product-041.jpg',24,1),
(3,'Toffee Pudding','Creamy layered toffee pudding served chilled.',1335.00,'Mini cup','assets/images/products/product-042.jpg',25,1),
(3,'Coconut Pudding','Creamy layered coconut pudding served chilled.',1390.00,'Mini cup','assets/images/products/product-043.jpg',26,1),
(3,'Coffee Pudding','Creamy layered coffee pudding served chilled.',1445.00,'Mini cup','assets/images/products/product-044.jpg',27,1),
(3,'Celebration Pudding','Creamy layered celebration pudding served chilled.',1500.00,'Mini cup','assets/images/products/product-045.jpg',28,1),

(4,'Butter Cookies Box','Freshly baked butter cookies packed for sharing.',895.00,'Box of 6','assets/images/products/product-046.jpg',26,1),
(4,'Chocolate Chip Cookies Box','Freshly baked chocolate chip cookies packed for sharing.',940.00,'Box of 6','assets/images/products/product-047.jpg',27,1),
(4,'Double Chocolate Cookies Box','Freshly baked double chocolate cookies packed for sharing.',985.00,'Box of 6','assets/images/products/product-048.jpg',28,1),
(4,'Oatmeal Raisin Cookies Box','Freshly baked oatmeal raisin cookies packed for sharing.',1030.00,'Box of 6','assets/images/products/product-049.jpg',29,1),
(4,'Coconut Cookies Box','Freshly baked coconut cookies packed for sharing.',1075.00,'Box of 6','assets/images/products/product-050.jpg',30,1),
(4,'Almond Cookies Box','Freshly baked almond cookies packed for sharing.',1120.00,'Box of 6','assets/images/products/product-051.jpg',31,1),
(4,'Vanilla Sugar Cookies Box','Freshly baked vanilla sugar cookies packed for sharing.',1165.00,'Box of 6','assets/images/products/product-052.jpg',32,1),
(4,'Coffee Cookies Box','Freshly baked coffee cookies packed for sharing.',1210.00,'Box of 6','assets/images/products/product-053.jpg',33,1),
(4,'Cinnamon Cookies Box','Freshly baked cinnamon cookies packed for sharing.',1255.00,'Box of 6','assets/images/products/product-054.jpg',34,1),
(4,'Salted Chocolate Cookies Box','Freshly baked salted chocolate cookies packed for sharing.',1300.00,'Box of 6','assets/images/products/product-055.jpg',35,1),

(5,'Classic New York Cheesecake','Creamy classic new york cheesecake with a crisp biscuit base.',3060.00,'6-inch','assets/images/products/product-056.jpg',13,1),
(5,'Blueberry Cheesecake','Creamy blueberry cheesecake with a crisp biscuit base.',3220.00,'6-inch','assets/images/products/product-057.jpg',14,1),
(5,'Strawberry Cheesecake','Creamy strawberry cheesecake with a crisp biscuit base.',3380.00,'6-inch','assets/images/products/product-058.jpg',15,1),
(5,'Chocolate Cheesecake','Creamy chocolate cheesecake with a crisp biscuit base.',3540.00,'6-inch','assets/images/products/product-059.jpg',16,1),
(5,'Mango Cheesecake','Creamy mango cheesecake with a crisp biscuit base.',3700.00,'6-inch','assets/images/products/product-060.jpg',17,1),
(5,'Caramel Cheesecake','Creamy caramel cheesecake with a crisp biscuit base.',3860.00,'6-inch','assets/images/products/product-061.jpg',18,1),
(5,'Lemon Cheesecake','Creamy lemon cheesecake with a crisp biscuit base.',4020.00,'6-inch','assets/images/products/product-062.jpg',19,1),
(5,'Coffee Cheesecake','Creamy coffee cheesecake with a crisp biscuit base.',4180.00,'6-inch','assets/images/products/product-063.jpg',20,1),
(5,'Oreo Style Cheesecake','Creamy oreo style cheesecake with a crisp biscuit base.',4340.00,'6-inch','assets/images/products/product-064.jpg',21,1),
(5,'Vanilla Bean Cheesecake','Creamy vanilla bean cheesecake with a crisp biscuit base.',4500.00,'6-inch','assets/images/products/product-065.jpg',22,1),

(6,'Fudge Brownie Box','Rich fudge brownies baked for a dense chocolate bite.',1270.00,'Box of 6','assets/images/products/product-066.jpg',23,1),
(6,'Walnut Brownie Box','Rich walnut brownies baked for a dense chocolate bite.',1340.00,'Box of 6','assets/images/products/product-067.jpg',24,1),
(6,'Double Chocolate Brownie Box','Rich double chocolate brownies baked for a dense chocolate bite.',1410.00,'Box of 6','assets/images/products/product-068.jpg',25,1),
(6,'Caramel Brownie Box','Rich caramel brownies baked for a dense chocolate bite.',1480.00,'Box of 6','assets/images/products/product-069.jpg',26,1),
(6,'Espresso Brownie Box','Rich espresso brownies baked for a dense chocolate bite.',1550.00,'Box of 6','assets/images/products/product-070.jpg',27,1),
(6,'Peanut Brownie Box','Rich peanut brownies baked for a dense chocolate bite.',1620.00,'Box of 6','assets/images/products/product-071.jpg',28,1),
(6,'Dark Cocoa Brownie Box','Rich dark cocoa brownies baked for a dense chocolate bite.',1690.00,'Box of 6','assets/images/products/product-072.jpg',29,1),
(6,'Sea Salt Brownie Box','Rich sea salt brownies baked for a dense chocolate bite.',1760.00,'Box of 6','assets/images/products/product-073.jpg',30,1),
(6,'Cookie Crumble Brownie Box','Rich cookie crumble brownies baked for a dense chocolate bite.',1830.00,'Box of 6','assets/images/products/product-074.jpg',31,1),
(6,'Classic Brownie Box','Rich classic brownies baked for a dense chocolate bite.',1900.00,'Box of 6','assets/images/products/product-075.jpg',32,1);